### PR TITLE
Fix #1: Ractive-Ractive leaks child instance's properties

### LINKED ISSUE #1: Ractive-Ractive leaks child instance's properties
While working with Ractive-Ractive I've noticed that the child Ractive's instance properties get exposed to the parent when using the parent's `get` and `set` methods.

When doing something like `parent.get("child.template");` instead of accessing `child` as if it was doing a `child.get("template");` it's actually just returning `child.template`.

I first noticed this was happening when my child instance had a `data` property defined within its `data` configuration (i.e.: `child.get("data");` - it's setup this way to match an external data source) and was receiving errors about Ractive trying to overwrite the `data` property when no setter was present (due to `ractive.data` now being inaccessible in Ractive v0.7.x), aka: it was trying to modify `child.data` directly rather than `child.set("data", ...)`.

I'll take a crack at seeing if there's a way to proxy directly to the child's data; however, I figured I'd ask for any advice / suggestions for this as a first step. Thanks for Ractive-Ractive! :)

### PR DESCRIPTION
**Pull request by ElliotChong**
Implemented method proxying / chaining based on keypath to fix #1.

If the keypath being accessed by the parent exists on a child Ractive instance then the method call is executed within the context of that child. This works recursively as well so nested references will still act as expected. Methods which update the data model notify the parent of updates and keep all references synchronized.

### CODE REVIEW

**Comment by rstacruz** [comment]
uh oh, looks like travis isnt enabled here, gotta get that fixed too

**Comment by rstacruz** [comment]
that's a huge change. can you add some tests in? I fear that functionality this huge really shouldn't go untested.

**Comment by ElliotChong** [comment]
@rstacruz Absolutely, that was my gameplan for this morning actually! :) Will ping you once I get them all in.

**Comment by ElliotChong** [comment]
@rstacruz I fixed up a bug I uncovered with `root` not being properly re-assigned on a child's grandchild when an inheritance chain was modified, added tests for leaking properties, and added tests for the `root` functionality. I've tested the latest codebase against a personal project and it seems solid, but I'd love more real-world validations to confirm everything is good to go if you're able. Let me know what you think!

**Comment by rstacruz** [comment]
hmmm

**Comment by rstacruz** [comment]
havent reviewed thoroughly yet — so this modifies the child ractive instances?

**Comment by rstacruz** [comment]
```js
    parent.set('child.template', 'templating');
    expect(child.template).equal(template);
    expect(child.get('template')).equal('templating');
```

i'm curious... i'm not sure why this is a good idea. it seems `.set('child.XXX')` will set both `XXX` the ractive data property, and the javascript object property. what case would this be useful in?

**Comment by rstacruz** [comment]
There's the concept of a `root` that i'm uncomfortable with. This makes this case rather ambiguous:

``` js
// used as some sort of model
var song = new Ractive({
  data: { title: "Wrecking Ball", artist: "Miley" }
});

// displays the song
var nowPlaying = new Ractive({
  data: { song: song }
});

// also displays the song
var playlistItem = new Ractive({
  data: { song: song }
});
```

**Comment by rstacruz** [comment]
Sorry buddy, you've obviously put a lot of work into this (thank you!) but ultimately I'll have to hold off on merging this in on the grounds that:
1. the use case of modifying the Ractive instance itself is something that will likely lead to surprising results.
2. storing an abundance of `_`-prefixed attributes in Ractive instances is something I wouldn't be comfortable in.
3. this more than doubles the project size to work on an edge case.

this is something that works right now:

``` js
parent.set('child', child);
child.set('template', 'jade');
parent.get('child.template') === 'jade'
```

and:

``` js
parent.set('child', child);
parent.set('child.template', 'jade');
child.get('template') === 'jade'
```

and this:

``` js
    it('doesnt bleed to instance properties', function () {
      var original = child.template;

      parent.set('child', child);
      parent.set('child.template', 'jade');
      expect(child.template).eql(original);
    });
```

sorry about this, but you're free to open up a fork if you feel this is wrong (i'll even help you!)

**Comment by rstacruz** [comment]
I've added some of the tests you had to the test suite:

https://github.com/rstacruz/ractive-ractive/commit/5777eb11c2604b2ca9609a73fed133e5b902e66e

Seems to work :)

**Comment by rstacruz** [comment]
btw, i may have missed something here i admit. if you'd like to continue on this, make a failing test case and we'll see what we can do.

**Comment by ElliotChong** [comment]
@rstacruz Hmm, I think you might have it backwards on the modification of the child instance... The current issue with master is that it DOES modify the child instance (such as that template example you posted, it currently clobbers the child instance's template property rather than modifying the child's data's template property). That's the entire point of this pull request: to properly encapsulate any manipulation to the child's `data` object, not the instance itself, by proxying all of the data-modifying method calls directly to the child and letting Ractive handle it.

The master version will literally set properties all over the Ractive instances, rather than modifying the data model.

I don't disagree with the point of storing `_` properties on Ractive as being a bit messy- I had actually originally taken a swipe at encapsulating them into an object just to tidy things up, but then ran into the downside that you'll need to manually marshal the context around (`this`) whenever you you need to call the original methods.

I concur that `root` isn't perfect due to the nature of a model being potentially accessible by multiple Ractive instances, but it does at least come a bit closer to matching Ractive's API of providing an easy accessor to the root Ractive instance. In the fairly common use-case of a single-Ractive instance (such as full page applications) you're only using a single main instance with components it will work fine and gives you the added benefit of being able to attach or dispatch events into a larger system.

Fundamentally I think proxying the methods of a parent to the child is really the way a Ractive adapter that is wrapping Ractive should work, but if you disagree it's your project at the end of the day. :)

**Comment by rstacruz** [comment]
> The current issue with master is that it DOES modify the child instance (such as that template example you posted, it currently clobbers the child instance's template property rather than modifying the child's data's template property).

Can you provide a test case for this? I've been trying to replicate it but it doesn't seem to happen.

**Comment by rstacruz** [comment]
> ...proxy all of the data-modifying method calls directly to the child and letting Ractive handle it.

The way I understand your changes work is that when doing `parent.set('child', child)`, it will modify parent's methods (such as `parent.set`) such that it will rewrite `parent.set('child.x', 'y')` into `parent.get('child').set('x', 'y')`.

This is not necessary. This is what Ractive handles for you by way of [adaptors](http://docs.ractivejs.org/latest/writing-adaptor-plugins). Ractive will delegate all child data modification to [adaptor.set](https://github.com/rstacruz/ractive-ractive/blob/v0.4.3/index.js#L149-L153). This will work for all Ractive instance methods like .increment, .pop, et al.

Here are some tests for that: https://github.com/rstacruz/ractive-ractive/blob/fa0edb7842aed4c1d/test/test.js#L463-L529

**Comment by rstacruz** [comment]
AHA!

>  it currently clobbers the child instance's template property rather than modifying the child's data's template property).

I just realized that this is the default behavior when you are actually _not_ using Ractive-ractive. Can you check?

``` js
parent.set('sub', child);
console.log(parent._ractiveWraps); // should be { sub: child } if it worked
```

This can happen if you have more than one Ractive loaded in your environment. Likely to happen when you are using 'ractive-runtime' (ractive-ractive defaults to using just `ractive`).

(cc @Rich-Harris — what's the consensus on loading Ractive in plugins again?)

**Comment by rstacruz** [comment]
Okay, v1.1.0 is out which allows you to use your own version of ractive (ie, it doesn't auto-load ractive by itself). See if that fixes your issue! [Details on upgrading here.](https://github.com/rstacruz/ractive-ractive/blob/master/HISTORY.md#v110---jul--2-2015)

**Comment by ElliotChong** [comment]
Sorry about that @rstacruz, I should have included a test for `data` in addition to the template one for clarity. This will actually throw an Error in Ractive 0.7.3 while illustrating the "leaking" I'm talking about (replace line 156 of test.js):

https://github.com/ElliotChong/ractive-ractive/commit/bfa9520e45beb40ca038a24517d22b52aa20b92c

``` javascript
    // https://github.com/rstacruz/ractive-ractive/pull/2/files
    it('proxies to a childs data object, not the instance properties', function () {
      var childTemplate = child.template;
      var parentTemplate = parent.template;

      var templatePropertyString = 'A property with the name `template`!';

      child.set('data', 'datum');
      child.set('template', templatePropertyString);

      // Setting a child on to a parent shouldn't try and modify instance-level properties
      parent.set('child', child);

      expect(child.get('data')).eql('datum');
      expect(parent.get('child.data')).eql('datum');

      parent.set('child.data', 'other_value');
      expect(child.get('data')).eql('other_value');

      // Getting a property on a child should access the child's `data`
      expect(parent.get('child.template')).eql(templatePropertyString);

      expect(child.template).eql(childTemplate);
      expect(parent.template).eql(parentTemplate);

      parent.set('child.template', 'templating');

      expect(child.template).eql(childTemplate);
      expect(parent.template).eql(parentTemplate);
      expect(child.get('template')).eql('templating');

      child.template = '<h1>Hello Test</h1>';
      expect(parent.get('child.template')).eql('templating');
      expect(child.get('template')).eql('templating');
    });
```

Also, here is a debugger screenshot showing the "leaking" I've been referring to:
image

The `name` properties that are leaking in are being defined here:
image

It might only apply to data which exists on a child before the `set` hooks are established, I'm not sure, but the getter is definitely accessing a child's instance properties directly in some cases rather than accessing the properties within its `data` object.

**Comment by ElliotChong** [comment]
To really illustrate the leak and make sure there's no ambiguity with `name`-

Properties which were present in the `data` object are ending up on Ractive instances:
image

image

**Comment by ElliotChong** [comment]
I've created another test case you can use to validate: https://github.com/ElliotChong/ractive-ractive/commit/9c863f532259e7fdba695823fda88a6a255d7dff

**Comment by rstacruz** [comment]
> https://github.com/ElliotChong/ractive-ractive/commit/9c863f532259e7fdba695823fda88a6a255d7dff

This case works on master (v1.1.0).

**Comment by rstacruz** [comment]
on a side note, what are you using to inspect those tests?

**Comment by ElliotChong** [comment]
[Node-inspector](https://github.com/node-inspector/node-inspector), it's awesome :) :+1: 

Install: `npm install node-inspector -g`
Launch: `node-inspector`
Launch: `mocha --debug-brk`
Point browser @: `http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858`

Re: https://github.com/ElliotChong/ractive-ractive/commit/9c863f532259e7fdba695823fda88a6a255d7dff working on Master, I have it freshly checked out with the tests inserted and seeing this:
image

Relevant Excerpts:

``` javascript
  describe('using with deeply-nested cases', function () {
    beforeEach(function () {
      subchild = new Ractive({ data: { name: 'subchild', subchildProperty: 'subchild property' }});
      child = new Ractive({ data: { name: 'child', childProperty: 'child property' }});
      parent = new Ractive({ data: { name: 'parent', parentProperty: 'parent property' }});
    });
```

``` javascript
    describe('organized linearly', function () {
      beforeEach(function () {
        parent.set('child', child);
        child.set('subchild', subchild);
      });
```

``` javascript
      it('doesn\'t leak data properties on to the Ractive instances', function () {
        expect(subchild.subchildProperty).be.undefined;
        expect(child.childProperty).be.undefined;
        expect(parent.parentProperty).be.undefined;
      });
```

**Comment by rstacruz** [comment]
I've added those tests now:

https://github.com/rstacruz/ractive-ractive/commit/a935db8e4edbe390ea64c37e378596dd320c6f97

You'll see them working here (yes! just implemented browser tests, too):

https://rawgit.com/rstacruz/ractive-ractive/master/test/index.html

**Comment by rstacruz** [comment]
Let's continue this discussion on #3 :)

**Pull request closed without merging**
